identity_uppercase:
  "A": "A"
  "B": "B"
  "C": "C"
  "D": "D"
  "E": "E"
  "F": "F"
  "G": "G"
  "H": "H"
  "I": "I"
  "J": "J"
  "K": "K"
  "L": "L"
  "M": "M"
  "N": "N"
  "O": "O"
  "P": "P"
  "Q": "Q"
  "R": "R"
  "S": "S"
  "T": "T"
  "U": "U"
  "V": "V"
  "W": "W"
  "X": "X"
  "Y": "Y"
  "Z": "Z"
identity_lowercase:
  "a": "a"
  "b": "b"
  "c": "c"
  "d": "d"
  "e": "e"
  "f": "f"
  "g": "g"
  "h": "h"
  "i": "i"
  "j": "j"
  "k": "k"
  "l": "l"
  "m": "m"
  "n": "n"
  "o": "o"
  "p": "p"
  "q": "q"
  "r": "r"
  "s": "s"
  "t": "t"
  "u": "u"
  "v": "v"
  "w": "w"
  "x": "x"
  "y": "y"
  "z": "z"
identity_digits:
  "0": "0"
  "1": "1"
  "2": "2"
  "3": "3"
  "4": "4"
  "5": "5"
  "6": "6"
  "7": "7"
  "8": "8"
  "9": "9"
punctuation:
  "$": "$"
  ";": ";"
  ":": ":"
  ",": ","
  ".": "."
  "!": "!"
  "?": "?"
  "¡": "¡"
  "¿": "¿"
  "—": "—"
  "…": "…"
  "\"": "\""
  "«": "«"
  "»": "»"
  "“": "“"
  "”": "”"
  "-": "-"
  "'": "'"
  "(": "("
  ")": ")"
  "/": "/"
  "+": "+"
  "%": "%"
  "#": "#"
  "&": "&"
  "@": "@"
  "[": "["
  "]": "]"
  "{": "{"
  "}": "}"
  "=": "="
  "|": "|"
  "_": "_"
  "^": "^"
  "~": "~"
arpabet_core:
  "AA": "ɑ"
  "AE": "æ"
  "AH": "ʌ"
  "AO": "ɔ"
  "AW": "aʊ"
  "AY": "aɪ"
  "B": "b"
  "CH": "tʃ"
  "D": "d"
  "DH": "ð"
  "EH": "ɛ"
  "ER": "ɝ"
  "EY": "eɪ"
  "F": "f"
  "G": "g"
  "HH": "h"
  "IH": "ɪ"
  "IY": "i"
  "JH": "dʒ"
  "K": "k"
  "L": "l"
  "M": "m"
  "N": "n"
  "NG": "ŋ"
  "OW": "oʊ"
  "OY": "ɔɪ"
  "P": "p"
  "R": "ɹ"
  "S": "s"
  "SH": "ʃ"
  "T": "t"
  "TH": "θ"
  "UH": "ʊ"
  "UW": "u"
  "V": "v"
  "W": "w"
  "Y": "j"
  "Z": "z"
  "ZH": "ʒ"
arpabet_extended:
  "AX": "ə"
  "AXR": "ɚ"
  "AX-H": "ə"
  "EM": "m"
  "EN": "n"
  "ENG": "ŋ"
  "NX": "ɾ"
  "Q": "ʔ"
  "DX": "ɾ"
  "EL": "l"
  "BCL": "b"
  "DCL": "d"
  "GCL": "g"
  "KCL": "k"
  "PCL": "p"
  "TCL": "t"
  "H#": "silence"
  "PAU": "silence"
  "SIL": "silence"
